import { Roboto } from "next/font/google";

import "./globals.css";
import Link from "next/link";
import Header from "./components/Header";

const inter = Roboto({ weight:["300", "700"], subsets: ["latin"] });

export const metadata = {
  title: "new shop center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>

        {children}
      </body>
    </html>
  );
}
